### ISSUE TITLE
Error GeoLite2-Country.mmdb

### ISSUE THREAD

**Issue by sokollondon** [wdmg/yii2-stats#2]
Продолжая https://github.com/wdmg/yii2-stats/issues/1
Пробовал установить `"wdmg/yii2-stats": "dev-master"`  последний коммит dd4af19. **Ошибка осталась.**
1) Можно использовать без GeoLite2?
2) Есть demo или screenshot как выглядит yii2-stats?

**Comment by alex-wdmg** [comment]
1) Да, вы правы... переменная public $maxmindLicenseKey должна быть по умолчанию false, чтобы не запрашивать базу GeoLite2. Пока что, попробуйте в модуле установить параметр в false или укажите ключ (можно получить на сайте [.maxmind.com](https://www.maxmind.com/) бесплатно).

2) Данный модуль часть системы [Butterfly.CMS](https://butterflycms.com). На сайте есть несколько скриншотов интерфейса данного модуля:
- [Stats Module: Visitors](https://butterflycms.com/img/screenshots/en/butterflycms-screenshot-22.png)
- [Stats Module: Visitors Details ](https://butterflycms.com/img/screenshots/en/butterflycms-screenshot-24.png)
- [Stats Module: Load Monitor](https://butterflycms.com/img/screenshots/en/butterflycms-screenshot-23.png)

**Comment by sokollondon** [comment]
Благодарю! Обновил и админка модуля показалась =)
