### ISSUE TITLE
Does not collect statistics

### ISSUE THREAD

**Issue by sokollondon** [wdmg/yii2-stats#3]
Тестирую на чистом [yii2-app-basic](https://github.com/yiisoft/yii2-app-basic) шаблоне.
Данные разделов "посетители" и "нагрузка" пустые.
Мой конфиг:

```
'modules' => [
    'stats' => [
        'class' => 'wdmg\stats\Module',
        'routePrefix' => '',
        'maxmindLicenseKey' => false,
        'ignoreListIp' => [],
    ],
],
```

Скриншоты:
https://yadi.sk/i/LmqDbT-k9UAuAA
https://yadi.sk/i/bR_n5TFuqk6ruw
https://yadi.sk/i/629oVWZ1JijN4A

Пробовал отключать 'YII_ENV', 'dev' и заходить через chrome в режиме инкогнито, не помогло.

**Comment by alex-wdmg** [comment]
Если вы используете модуль как stand alone (модуль без родителя) необходима ещё его инициализация в конфиге:
`
$config['bootstrap'][] = 'stats';
`
... или посредством вызова метода в приложении:
`
Yii::$app->getModule('stats', true);
`

Попробуйте, и отпишитесь пожалуйста.

**Comment by sokollondon** [comment]
Вызов `Yii::$app->getModule('stats', true);` в actionAbout() контроллера эффекта не дало.

Добавление `$config['bootstrap'][] = 'stats';` помогло, статистика появилась https://yadi.sk/d/1mg-zuTgyjXZkA =) Только все страницы сайта стали 404 https://yadi.sk/i/d7hiWVZPswG8pg

**Comment by sokollondon** [comment]
Обновился. Страницы отображаются все кроме одной `/stats` https://yadi.sk/i/Ae_AfSYok0U_Vw  возможно заменить её в меню на `/stats/visitors` которая отображается без ошибок?
